server:
  port: 8222

spring:
  application:
    name: api_gateway
  cloud:
    #nacos服务注册与发现
    nacos:
      discovery:
        server-addr: localhost:8848
    #api网关
    gateway:
      discovery:
        locator:
          #开启网关
          enabled: true
      #路由匹配规则  lb:  load balance 负载均衡
      routes:
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduservice/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduoss/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/eduvod/**
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/educms/**
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/edumsm/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/eduorder/**
        - id: service-sta
          uri: lb://service-sta
          predicates:
            - Path=/edusta/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/educenter/**
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/admin/acl/**







